#!/usr/bin/env bash
# Assembles per-agent instruction files in dist/ from source fragments in fragments/.
# Run this script whenever fragments change, or let install-skills.sh call it automatically.

set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
F="$REPO/fragments"
D="$REPO/dist"

HEADER="<!-- Auto-generated by scripts/build.sh — edit fragments/, not this file -->"

mkdir -p "$D"

# ── OpenCode: AGENTS.md ────────────────────────────────────────────────────────
# Plain markdown (no YAML frontmatter). Contains universal core + Python section
# + Context7. No RTK — RTK is handled transparently by the OpenCode plugin.
{
  echo "$HEADER"
  echo ""
  cat "$F/universal.md"
  echo ""
  cat "$F/python.md"
  echo ""
  cat "$F/context7.md"
} > "$D/AGENTS.md"

# ── Cursor: engineering standards ─────────────────────────────────────────────
# YAML frontmatter + universal core + Python section.
{
  echo "$HEADER"
  echo ""
  cat "$F/frontmatter-cursor-standards.md"
  echo ""
  cat "$F/universal.md"
  echo ""
  cat "$F/python.md"
} > "$D/engineering-standards.mdc"

# ── Cursor: Context7 rule ──────────────────────────────────────────────────────
# Separate rule file with YAML frontmatter.
{
  echo "$HEADER"
  echo ""
  cat "$F/frontmatter-cursor-context7.md"
  echo ""
  cat "$F/context7.md"
} > "$D/context7.mdc"

echo "Built dist/:"
for f in "$D"/*; do
  printf "  %-35s (%d lines)\n" "$(basename "$f")" "$(wc -l < "$f")"
done
