#!/usr/bin/env bash
# Assembles per-agent instruction files in dist/ from source fragments in fragments/.
# Run this script whenever fragments change, or let install-skills.sh call it automatically.

set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
F="$REPO/fragments"
D="$REPO/dist"

HEADER="<!-- Auto-generated by scripts/build.sh — edit fragments/, not this file -->"

mkdir -p "$D"

# ── Claude Code ────────────────────────────────────────────────────────────────
# Contains: frontmatter + universal core + Python section + RTK (hook model)
# Context7 for Claude Code is managed separately in ~/.claude/rules/context7.md
# and is NOT included here (the installer symlinks fragments/context7.md there).
{
  echo "$HEADER"
  echo ""
  cat "$F/frontmatter-claude.md"
  echo ""
  cat "$F/universal.md"
  echo ""
  cat "$F/python.md"
  echo ""
  cat "$F/rtk-claude.md"
} > "$D/CLAUDE.md"

# ── Codex ──────────────────────────────────────────────────────────────────────
# Contains: universal core + Python section + RTK (manual prefix model) + Context7
# No YAML frontmatter — Codex reads AGENTS.md as plain markdown.
# Fully self-contained: no @include dependencies.
{
  echo "$HEADER"
  echo ""
  cat "$F/universal.md"
  echo ""
  cat "$F/python.md"
  echo ""
  cat "$F/rtk-codex.md"
  echo ""
  cat "$F/context7.md"
} > "$D/AGENTS.md"

# ── Cursor: engineering standards ─────────────────────────────────────────────
# Contains: frontmatter + universal core + Python section
# No RTK (Cursor does not use it).
{
  echo "$HEADER"
  echo ""
  cat "$F/frontmatter-cursor-standards.md"
  echo ""
  cat "$F/universal.md"
  echo ""
  cat "$F/python.md"
} > "$D/engineering-standards.mdc"

# ── Cursor: Context7 rule ──────────────────────────────────────────────────────
# Separate rule file so Cursor can manage it independently of engineering standards.
{
  echo "$HEADER"
  echo ""
  cat "$F/frontmatter-cursor-context7.md"
  echo ""
  cat "$F/context7.md"
} > "$D/context7.mdc"

echo "Built dist/:"
for f in "$D"/*; do
  printf "  %-35s (%d lines)\n" "$(basename "$f")" "$(wc -l < "$f")"
done
